{% set version = "3.1.0" %}

package:
  name: social-auth-app-django
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-app-django/social-auth-app-django-{{ version }}.tar.gz
  sha256: 6d0dd18c2d9e71ca545097d57b44d26f59e624a12833078e8e52f91baf849778

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - social-auth-core >=1.2.0

test:
  imports:
    - social_django
    - social_django.migrations

about:
  home: https://github.com/python-social-auth/social-app-django
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Python Social Authentication, Django integration.'

extra:
  recipe-maintainers:
    - ocefpaf
