{% set version = "4.0.0" %}

package:
  name: social-auth-app-django
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/social-auth-app-django/social-auth-app-django-{{ version }}.tar.gz
  sha256: 2c69e57df0b30c9c1823519c5f1992cbe4f3f98fdc7d95c840e091a752708840

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - social-auth-core >=3.3.0

test:
  imports:
    - social_django
    - social_django.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-social-auth/social-app-django
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python Social Authentication, Django integration.

extra:
  recipe-maintainers:
    - ocefpaf
