travis:
  secure:
    BINSTAR_TOKEN: g+0ZgDJLSDE2SNG7BIF+CJVNR5B/Eg+mDzFPaTUeh+t2+irMMf/qMxrVHlQ7yyLqqsvU7ivTOJMgvdyh7fgOXgbYtGmdEJyjncI56oQosANq3tGsM/79/5Ir7EubF6aguzQV27L/kmXZghJESsRnkSIchijaOgtPeUlGtscCfMxKbz9CzICOt0+T1CffEKvjFahiqq/Qi16Lpo9jsmmyGtR9r1I4RaCT3mg9PuYVIr5P2Q8Dc0ITcrtbqaEoZHrsQDbVgIvhlGlLsB2ae5hvWQH1ffHQCnI40I+8F5l/YzrBG6wZysLUr7HMGaq7RePe5pfowKA4vqQuXGZJ4oxoYtVC82cUrVtnR0qT3VV30RM6gJ/woQ9YhA4h1Y3RHfsdC9ICwSWCJhpcELnmnnq3codvMLPG+60wcwKNsoWzq97FJmN1oNa716IbFVz6VJ92WVtxkeU3EXlhPG5qN/XA6zzQ0wAT0WPhBHMx4b6cFFicOauuHTto2rmrNA9CQ3ELIsV6uZPhpXIifdSOZ1fQQWBB1bQqpY6lkR70HkChol88oRBd8V/aHbwW+ITXldZQCctXjTNUAZN9G04yjrCI8QTAbxvEj8uEgYvB5sm9kVc0fvPuGRWoXV5CXNBKtGfvpY+Tb3h80GYq5jMFzPDXMSdUAf1ep84wb756B3+rCFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
