travis:
  secure:
    BINSTAR_TOKEN: CBpmYVs32qs2w26jbpdqXiNenbYV4SojRJy0I2hjD+ksMrWfGsuIEvg1J+Ec/LHXCEaYzOYw+6El2prdcW/+gya23dPmSujFyf2Q/mZgJjM0QhxZnOPhTLGebTlMRi2nuKog8lQBSz7CYWiSSFa0+TMx4ZvCTvBwK4oz9eAn82EBEDefseuWoKJRZs29p99a5zKCjhC17/TE0yimRA5zK2U6tWLTbLCdgAj+vWJUjrMI7kn+Hqev+2+gG1+LgR+4loHr0ylOBEpJ2jf4ka+Sc5OL74/ZDtOkHlaNOS/6wTC5J/8IiEKhuzuyZm9hoq2BQG6R9Yu7JMijo6+iVSHyljJGoKKl5igBU1joxU9jZDXpZtRDJsNf3i69S5oj6OBC3Uk1mi5k138KJTa4rR9ZYkmmHwvp0kRyumt412FvMOxE+ALll+1QQc1JqTrqw5H3lHiihQDsfQ62WTu9jIJ/oQL991FJ+8M1bCatIK2o4V9s+vNn6rx2d7LiFjHnCb6V0SMy1W2xU5xIee2jA+IBWwg9/IL6zdKBLob7L4vbN5qhyGor4FOQ4qLFRVmwxEV1sv3aSgqqLJzdlwZnYpvsllG2wfVqAvlSM0GyC4o9ktfUzsApp+zZtALaRrqDRZ5q3J+jP+HAhFEi97nOiqu6GNRvtplqCbOhaouHocl/c5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
